### ISSUE TITLE
[Wait for ship to land] bug

### ISSUE THREAD

**Issue by Snayp1** [ImTerm/UnknownWeather#1]
When you leave a planet with the mod unabled, you won't be able to start a new mission as the lever will say forever "Wait for ship to land"
There is an error in the terminal causing this bug.
![Capture d'éc![Capture d'écran 2024-01-21 000842](https://github.com/ImTerm/UnknownWeather/assets/145205376/7886625b-d796-4b1e-aea3-e437f715c481)
Sometimes the bug would happen on the first day and sometimes on day 3 (I can't remember it ever happening on day 2 but i don't know)

I've spent 3 hours trying to understand from where this error was coming from, I wouldn't have supected this mod to be the cause.
I really like the concept of this mod so I hope it get fixed.

**Comment by ImTerm** [comment]
Thanks for your dedication to helping! I think I just realized what's causing this mess. Some coroutine in the main game must be affecting the text on the monitor at the same time as my patch, and my code that splits and removes the weather text is sometimes at the point between when it found the match and when it is attempted to be removed. Will be looking into a fix tonight.

**Comment by ImTerm** [comment]
I was able to reproduce this bug consistently and implement a fix. Released the update just now!

**Comment by Snayp1** [comment]
Thank you! It seems to be working fine now! Thanks for taking the time, I was worried it would never be fixed

**Comment by Snayp1** [comment]
Also I have a suggestion
I think it would be nice to have an unlockable upgrade to be able to know the weather. I don't know about the price but it could be something like 200.
What do you think?

**Comment by ImTerm** [comment]
I like the idea of being able to perform a weather scan for the day at a certain price. I've been meaning to mess around with configs, and this would be the perfect time to try it out. I'll try to work on an update that implements the weather scan and a config option to allow you to choose whether it's instead a permanent upgrade to the ship or remove it altogether as non-default options if the player wishes
